CREATE TABLE "follow_up_notice" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "follow_up_notice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source" text NOT NULL,
	"source_id" text NOT NULL,
	"title" text NOT NULL,
	"kind" text,
	"published_at" text,
	"source_url" text NOT NULL,
	"related_source_id" text,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"raw" jsonb
);
--> statement-breakpoint
CREATE TABLE "housing_unit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "housing_unit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source" text NOT NULL,
	"source_key" text,
	"notice_id" integer,
	"inst_name" text,
	"sido" text,
	"sigungu" text,
	"complex_name" text,
	"address" text,
	"pnu" text,
	"unit_no" text,
	"supply_type" text,
	"house_type" text,
	"exclusive_area" numeric(8, 2),
	"common_area" numeric(8, 2),
	"household_count" integer,
	"total_household" integer,
	"deposit" bigint,
	"monthly_rent" bigint,
	"heating" text,
	"parking_count" integer,
	"built_on" text,
	"value_source" text DEFAULT 'official' NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notice" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source" text NOT NULL,
	"source_id" text NOT NULL,
	"title" text NOT NULL,
	"agency" text DEFAULT '기타' NOT NULL,
	"inst_name" text,
	"notice_type" text,
	"notice_type_norm" text,
	"region" text,
	"districts" text[] DEFAULT '{}'::text[] NOT NULL,
	"published_at" text,
	"apply_start" text,
	"apply_end" text,
	"apply_deadline_at" timestamp with time zone,
	"announce_at" text,
	"status" text,
	"supply_count" text,
	"source_url" text NOT NULL,
	"before_source_id" text,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"raw" jsonb
);
--> statement-breakpoint
CREATE TABLE "sync_run" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sync_run_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"trigger" text DEFAULT 'manual' NOT NULL,
	"status" text DEFAULT 'running' NOT NULL,
	"sources" jsonb,
	"error" text
);
--> statement-breakpoint
ALTER TABLE "housing_unit" ADD CONSTRAINT "housing_unit_notice_id_notice_id_fk" FOREIGN KEY ("notice_id") REFERENCES "public"."notice"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "follow_up_source_key" ON "follow_up_notice" USING btree ("source","source_id");--> statement-breakpoint
CREATE UNIQUE INDEX "housing_unit_source_key" ON "housing_unit" USING btree ("source","source_key");--> statement-breakpoint
CREATE INDEX "housing_unit_area_rent" ON "housing_unit" USING btree ("sigungu","exclusive_area","deposit");--> statement-breakpoint
CREATE INDEX "housing_unit_notice" ON "housing_unit" USING btree ("notice_id");--> statement-breakpoint
CREATE INDEX "housing_unit_pnu" ON "housing_unit" USING btree ("pnu");--> statement-breakpoint
CREATE UNIQUE INDEX "notice_source_key" ON "notice" USING btree ("source","source_id");--> statement-breakpoint
CREATE INDEX "notice_apply_end" ON "notice" USING btree ("apply_end");--> statement-breakpoint
CREATE INDEX "notice_first_seen" ON "notice" USING btree ("first_seen_at");--> statement-breakpoint
CREATE INDEX "sync_run_started" ON "sync_run" USING btree ("started_at");